name: Project 1 website deploy

on:
  push:
    branches:
      - gh-pages-project-1
      - main

jobs:
  publish:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Current workdir (which contains generated content) to GitHub Pages
        uses: rayluo/github-pages-overwriter@v1.3

        with:
          source-directory: Projekt_1
